#
# GitHub Actions workflow: Builds and tests the code in this repository.
#
# For more details on workflows, see README.md.
#

# IMPORTANT: When changing this name, also change the name in the trigger section in "test-report.yaml".
name: CI

# When to run this workflow
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  # Trigger the workflow on push or pull request, but only for the main branch.
  # Reason: Until a feature branch is converted into a pull request, there's no (real) need
  #   to have this workflow waste resources and trigger 'workflow did not work' emails.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Permissions for GITHUB_TOKEN for this workflow.
#   See: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
# NOTE: Because of this, we don't use "@hash" but "@vX" for non-GitHub steps below. Usually you would use "@hash"
#   as a security measure to pin a specific version. However, since we run with the minimal permissions
#   here, malicious code couldn't do much harm (most likely).
#   See: https://blog.gitguardian.com/github-actions-security-cheat-sheet/#use-specific-action-version-tags
permissions:
  contents: read

jobs:
  build-and-test:
    # Name the job
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yaml
